name: Art Streaker
favicon: null
layout_spectrum: 0.6337877963669598
typography_spectrum: 0.30959014571271837
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5656646825373173
  lightness: 0.028896114556118846
  saturation: 0.7621845647227019
  rhythmicContrast: 0.8821471419651061
purpose: []
